#!/usr/bin/env ruby

CMD = File.join(File.dirname(__FILE__), 'kondate')
if ARGV.size == 0 || ARGV[0] == "-h" || ARGV[0] == "--help"
  exec CMD, 'help', 'serverspec-role'
else
  exec CMD, 'serverspec-role', *ARGV
end
